name: qligfep
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - ld_impl_linux-64=2.36.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libgomp=12.1.0
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.20
  - libstdcxx-ng=12.1.0
  - libuuid=2.32.1
  - libzlib=1.2.11
  - ncurses=6.3
  - numpy=1.22.3
  - openssl=3.0.3
  - pip=22.1
  - python=3.10.4
  - python_abi=3.10
  - readline=8.1
  - setuptools=62.2.0
  - sqlite=3.38.5
  - tk=8.6.12
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
